#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure RbHello
#

require "autorake/mkconfig"

Autorake.configure {

  extending_ruby

  if RUBY_VERSION < "1.9" then
    have_header "ruby.h"
  else
    have_header "ruby/ruby.h"
  end

}

