#
#  Rakefile  --  build some libraries
#


require "rake/autorake"

extend Rake::Configure


puts "Features enabled:"
puts "Some  - #{p_some_feature}"
puts "Other - #{other_feature?}"
puts "Foo   - #{foo}"
# Use these in if-like statements.


rule ".o" => ".c" do |t|
  cc t.name, t.source, "-O2", "-fPIC"
end


DLs = {
  "notempty.so"  => "notempty.o",
}

DLs.each { |k,v|
  task k => v do |t|
    ld t.name, t.prerequisites, "-shared"
  end
}


task :default => DLs.keys


task :clean do
  FileList[ "*.o", "*.so"].each { |f| rm_f f }
end



# Here are some installers. They may be called by
#
#   $ rake install
#
# This is in case your project cannot be provided as a gem.
#
# For testing purposes you may call
#
#   $ ./mkrf_conf --destroot /tmp/testroot --disable-dummy
#   $ rake
#   $ rake install
#   $ find /tm/testroot -type f
#
# You can find all install directories in the file ".configure".
# See "./mkrf_conf --help" for the configuration facilities.
#

ruby_version = RUBY_VERSION.slice %r/\A\d+\.\d+/

%w(
  notempty.so
).map { |e|
  installer e, [ :lib, "ruby", "site_ruby", ruby_version]
}   
    
%w(
  echoit
).map { |e|
  installer e, [ :bin], :shebang => true
}

task :install do
  puts "Installation done."
end

