#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure Hello
#

require "autorake/mkconfig"

Autorake.configure {

  have_header "stdio.h"

  disable :now do
    with :foo, "dummy"
    # incdir :bar, "/path/to/bar"
    # libdir :baz, "/path/to/baz"
  end

}

