#
#  Rakefile  --  build executable
#

require "autorake"

c = compiler "-O2"
l = linker

rule ".o" => ".c" do |t|
  c.cc t.name, t.source
end

task "hello" => "hello.o" do |t|
  l.cc t.name, t.prerequisites
end

task :default => "hello"

task :clean do
  FileList[ "*.o", "hello"].each { |f| rm_f f }
end

task :foo do
  puts parameter(:foo)
end

