#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure installer
#

require "autorake/mkconfig"

Autorake.configure {

  directory :vim,      "DATA/vim"
  directory :vimfiles, "VIM/vimfiles"

  disable :dial

  with :user,  "games"
  with :group, "games"

}

