#
#  Rakefile  --  install the files
#

require "autorake"

task :default

task :clean


# Installers

vims = %w(
  plugin/ruby.vim
  plugin/yesno.vim
)

if has? :dial then
  vims.concat %w(
    plugin/dial.vim
  )
end

if Process.uid == 0 then
  ug = { :user => parm[ :user], :group => parm[ :group] }
end

task :install do
  dst = expand "VIMFILES"
  puts "Installing files to '#{dst}'."
end

installer vims, "VIMFILES", ug

