#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure Hello
#

require "autorake/mkconfig"


# This example transports parameters into the C code of the project
# by writing a special config header containing #defines.
#
# A more convenient way to do such things is using the "with" mode
# for directories as shown in other examples. But if you prefer this
# method you can also do so.


module Autorake

  class MkConfigHeader < MkConfig

    HEADER = "config.h"

    CONSTANTS = %w(MYPROJ)

    def made
      require "autorake"
      extend Autorake::Rakefile   # This defines the "expand" method used below.
      File.open HEADER, "w" do |f|
        CONSTANTS.each { |c|
          e = expand c
          f.puts '#define DIR_%s "%s"' % [c, e]
        }
      end
    end

    def cleaned
      File.unlink HEADER if File.file? HEADER
    end

  end


  configure {

    directory :myproj, "PREFIX/myproj"

  }

end

